import logo from './Banner.jpg';
export default function BlankSpace(){
    return <div>
        <img src={logo} style={{width:1690}}/>
        <div className="strip"> 
           <center><h2> Apply Knowledge Improve Life</h2>  </center> 
        </div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit magni explicabo at labore itaque facere, similique recusandae impedit suscipit tempore aliquam architecto, sunt doloribus ex quod, dolorum voluptatum perferendis dolorem cum hic sapiente accusamus rerum. Praesentium voluptates atque dicta in tempora velit repellat, animi aliquam! Eveniet veritatis, necessitatibus rem dolore soluta magnam accusantium sit officia. Sed at soluta dolorum incidunt, ipsa est cupiditate vitae consequuntur iste distinctio eum? Odio repudiandae ducimus qui tenetur ut, aut quam nam beatae dolorum error nulla neque, vitae unde. Neque dicta consequatur perferendis soluta cumque magni, impedit enim perspiciatis dolor quibusdam. Officia, ad.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus, in rerum doloremque odit nemo distinctio. Delectus, ducimus natus at doloremque, ullam eos quam inventore magni ut qui molestiae. Omnis, temporibus eius atque totam quod earum, nostrum corrupti soluta minima cumque, nemo laboriosam perferendis cum vero repellat autem quo modi ratione magnam ipsam. Voluptatem possimus ad voluptates eos iure labore quae? Reiciendis, tempore debitis porro assumenda magnam beatae?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque obcaecati corporis quia quae similique. Natus mollitia, quod recusandae repellendus quasi facilis modi quisquam sequi aut. Itaque aliquid dicta vel id ut optio porro tenetur pariatur, ab illum obcaecati corrupti doloremque corporis doloribus ducimus dignissimos alias adipisci autem. At itaque libero doloribus et atque eos odio beatae culpa perferendis. Atque adipisci perspiciatis sed accusantium similique accusamus suscipit at doloribus molestias, nesciunt deserunt, minus magnam modi iste itaque? Cupiditate quis voluptatibus consequuntur laboriosam, praesentium distinctio. Explicabo autem enim ex, asperiores aut aliquam commodi nostrum cum distinctio sint officiis. Eaque, vitae distinctio?Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat eum nesciunt explicabo ex odio cum at eaque itaque quisquam debitis nostrum rem aut voluptatem, est natus! Consequatur laudantium eos sed nesciunt, perspiciatis vero ipsum adipisci nemo ab dolores ipsam, excepturi iusto delectus quam asperiores obcaecati libero aperiam expedita doloremque et, suscipit reprehenderit. Ullam quae vel atque iure tempore, sequi nihil ut facilis obcaecati ex voluptatibus, placeat nulla est et. Vel vero repellat quisquam omnis, ab saepe veniam fugit maiores in deleniti quibusdam recusandae architecto molestias labore.
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aspernatur obcaecati optio laborum distinctio provident est aliquid quis totam impedit quas delectus mollitia deleniti eaque voluptate perferendis fugit praesentium repudiandae molestiae sed sint, perspiciatis, inventore nam fugiat? Quod, aspernatur cupiditate alias asperiores incidunt sit quia nobis adipisci deleniti, ipsa totam voluptate illo deserunt sapiente non dolores. Odio ex, corrupti deleniti numquam et doloremque similique cupiditate velit quas iusto obcaecati, placeat vitae voluptate repellendus! Dolorum quod itaque nesciunt quia, molestiae eligendi quis repudiandae officia quaerat perspiciatis, vitae minima ex esse fugiat. Vel ea recusandae ad fuga iste doloremque adipisci, magnam blanditiis.
        
       
        </div>
}